In [11]:
import pandas as pd

df = pd.read_csv('../src/main/resources/SampleGameTitle.csv')

# Quick Analysis: the csv consist of 2000 plus unique game title.
print(f"There are {df['game_name'].unique().size} unique game title")

df.info

There are 2133 unique game title

<bound method DataFrame.info of                game_name game_code  type  cost_price   tax  sale_price
0         Counter-Strike        pc     2        9.17  0.09        9.99
1          Day of Defeat        pc     2        4.58  0.09        4.99
2     Deathmatch Classic        pc     2        4.58  0.09        4.99
3               Ricochet        pc     2        4.58  0.09        4.99
4        Team Fortress 2        pc     2        0.00  0.09        0.00
...                  ...       ...   ...         ...   ...         ...
2159           Bamboo EP        pc     2        0.00  0.09        0.00
2160    Shot Shot Tactic        pc     2        3.66  0.09        3.99
2161                 Ra2        pc     2        0.00  0.09        0.00
2162       Paintball 707        pc     2        4.58  0.09        4.99
2163          Technoball        pc     2        0.00  0.09        0.00

[2164 rows x 6 columns]>

Use the code below to randomize the title. Also, it takes the first 100 rows. With that, the game_no (as per requirement 1 to 100) is then assigned.

In [26]:
#  Random the sequence
randomized = df.sample(frac=1, ignore_index= True)
randomized.reset_index(drop=True)
randomized.head(50)

               game_name game_code  type  cost_price   tax  sale_price
0           Kingdom Wars        pc     1        0.00  0.09        0.00
1                 ONRAID        pc     1        9.17  0.09        9.99
2       Mysterious Space        pc     2        9.17  0.09       10.00
3            Gemini Wars        pc     2       13.75  0.09       14.99
4           Actua Golf 3        pc     2        4.58  0.09        4.99
5          Path of Exile        pc     1        0.00  0.09        0.00
6          Insecters War        pc     2        0.00  0.09        0.00
7             Scary Girl        pc     2        6.41  0.09        6.99
8          Rally Copters        pc     2        6.41  0.09        6.99
9               NBA 2K17        pc     2       55.04  0.09       59.99
10                  Crea        pc     2       13.75  0.09       14.99
11            Hauntsters        pc     2        4.58  0.09        4.99
12             Sky Rogue        pc     2        9.17  0.09        9.99
13            MapleStory        pc     1        0.00  0.09        0.00
14           Below Kryll        pc     2        4.58  0.09        4.99
15               Alganon        pc     1        0.00  0.09        0.00
16             Jamestown        pc     2        9.17  0.09        9.99
17              Positron        pc     2        0.00  0.09        0.00
18           ManaCollect        pc     2        2.56  0.09        2.79
19             WolfQuest        pc     2        9.17  0.09        9.99
20      Lost Planet(r) 2        pc     2       18.34  0.09       19.99
21           Bombernauts        pc     2        9.17  0.09        9.99
22    AoF Chess Club 2.0        pc     2        9.17  0.09        9.99
23  Total War: WARHAMMER        pc     2       55.04  0.09       59.99
24           Lost Castle        pc     2        9.17  0.09        9.99
25              Altitude        pc     2        0.00  0.09        0.00
26          Oh No! Bugs!        pc     2        4.58  0.09        4.99
27   Pixel Cup Soccer 17        pc     2        9.17  0.09        9.99
28                Chaser        pc     2        4.58  0.09        4.99
29      Rivals of Aether        pc     2       13.75  0.09       14.99
30    Jet Racing Extreme        pc     2        3.66  0.09        3.99
31                Impire        pc     2       18.34  0.09       19.99
32       Galaxy Admirals        pc     2        1.83  0.09        1.99
33             Dark Eden        pc     1        0.00  0.09        0.00
34         Tricky Towers        pc     2       13.75  0.09       14.99
35                Arma 2        pc     2       11.92  0.09       12.99
36            Blockships        pc     2        6.41  0.09        6.99
37               Butsbal        pc     2        2.74  0.09        2.99
38      Ms. Splosion Man        pc     2        9.17  0.09        9.99
39                 CATS!        pc     2        9.17  0.09        9.99
40  Random Access Murder        pc     2        2.74  0.09        2.99
41            DiRT Rally        pc     2       55.04  0.09       59.99
42               SinaRun        pc     2        2.74  0.09        2.99
43        T-Kara Puzzles        pc     2        2.74  0.09        2.99
44           BattleSpace        pc     1        0.00  0.09        0.00
45    Chicken Invaders 2        pc     2        3.66  0.09        3.99
46        Sphere Complex        pc     2        9.17  0.09        9.99
47              The Isle        pc     2       18.34  0.09       19.99
48          Blind Blades        pc     2        4.58  0.09        4.99
49                 BRINK        pc     2        7.33  0.09        7.99

In [28]:
randomized.index += 1
randomized[:100].to_csv('../src/main/resources/100GameTitle.csv',index_label='game_no')

In [141]:
import numpy as np
def random_dates(start, end, n, freq, seed=None):
    if seed is not None:
        np.random.seed(seed)

    dr = pd.date_range(start, end, freq=freq)
    return pd.to_datetime(np.sort(np.random.choice(dr, n, replace=False)))

random_dates('2024-04-01', '2024-04-30', 91, 's', seed=None)

DatetimeIndex(['2024-04-01 02:53:43', '2024-04-01 09:41:53',
               '2024-04-02 18:37:53', '2024-04-03 02:54:37',
               '2024-04-03 16:23:26', '2024-04-03 17:28:05',
               '2024-04-03 19:00:42', '2024-04-04 12:51:29',
               '2024-04-04 14:52:16', '2024-04-04 15:03:36',
               '2024-04-04 20:32:38', '2024-04-05 05:02:50',
               '2024-04-05 09:28:12', '2024-04-05 10:57:56',
               '2024-04-05 23:55:47', '2024-04-06 07:41:14',
               '2024-04-06 11:32:06', '2024-04-06 17:34:52',
               '2024-04-06 19:15:50', '2024-04-07 05:48:03',
               '2024-04-07 06:57:40', '2024-04-07 07:19:26',
               '2024-04-07 10:56:41', '2024-04-07 15:09:32',
               '2024-04-07 20:01:17', '2024-04-08 13:52:00',
               '2024-04-08 17:39:18', '2024-04-09 09:25:06',
               '2024-04-09 17:23:50', '2024-04-10 11:14:30',
               '2024-04-10 11:40:31', '2024-04-10 12:57:13',
               '2024-04-10 16:26:33', '2024-04-11 03:44:13',
               '2024-04-11 06:55:14', '2024-04-11 10:42:24',
               '2024-04-12 09:29:13', '2024-04-12 14:16:46',
               '2024-04-12 15:40:20', '2024-04-12 17:37:29',
               '2024-04-13 00:58:30', '2024-04-13 04:48:00',
               '2024-04-13 19:29:12', '2024-04-14 00:11:29',
               '2024-04-14 11:50:18', '2024-04-14 16:11:57',
               '2024-04-15 02:33:28', '2024-04-16 19:53:09',
               '2024-04-17 01:46:42', '2024-04-17 01:59:30',
               '2024-04-17 07:30:58', '2024-04-17 15:07:12',
               '2024-04-18 00:02:17', '2024-04-18 01:14:07',
               '2024-04-18 13:30:36', '2024-04-18 15:44:57',
               '2024-04-19 00:42:38', '2024-04-19 02:28:12',
               '2024-04-19 04:34:48', '2024-04-19 09:37:29',
               '2024-04-19 20:42:17', '2024-04-20 08:38:08',
               '2024-04-20 13:51:22', '2024-04-20 14:28:33',
               '2024-04-20 21:35:35', '2024-04-21 03:12:23',
               '2024-04-21 22:38:40', '2024-04-22 10:19:38',
               '2024-04-22 16:58:23', '2024-04-23 04:47:54',
               '2024-04-23 10:27:06', '2024-04-23 11:09:08',
               '2024-04-23 14:14:04', '2024-04-23 16:33:06',
               '2024-04-24 07:01:30', '2024-04-24 12:43:25',
               '2024-04-24 18:33:19', '2024-04-24 22:54:19',
               '2024-04-25 01:04:30', '2024-04-25 02:24:32',
               '2024-04-26 00:43:24', '2024-04-26 02:26:23',
               '2024-04-26 04:03:55', '2024-04-26 17:50:51',
               '2024-04-26 18:19:27', '2024-04-27 03:02:58',
               '2024-04-27 04:24:09', '2024-04-27 14:01:32',
               '2024-04-28 04:54:20', '2024-04-28 16:58:14',
               '2024-04-28 21:42:04'],
              dtype='datetime64[ns]', freq=None)

# Using this to quickly generate 1K game_sales records.

In [146]:
import random
df = pd.read_csv('../src/main/resources/100GameTitle.csv')


arTime = random_dates('2024-04-01', '2024-04-30', 100, 's', seed=None)
df["date_of_sale"]=df.apply(lambda row: arTime[row.name], axis=1)

multiplier = 20
while len(df) < 1000:
    p=random.randint(2,100)
    toMultiply=df[p-1:p]
    toMultiply = pd.concat([toMultiply] * multiplier, ignore_index = True)
    arTime = random_dates('2024-04-01', '2024-04-30', multiplier, 's', seed=None)
    toMultiply["date_of_sale"]=toMultiply.apply(lambda row: arTime[row.name], axis=1)

    df = pd.concat([df, toMultiply], ignore_index = True)


df = df.sample(frac=1, ignore_index= True)
# df.reset_index(drop=True)

# df.index += 1
df.to_csv('../src/main/resources/gameTitlesOneK.csv',index=False)

# Using this to quickly generate 1M game_sales records.

In [147]:
import random
df = pd.read_csv('../src/main/resources/100GameTitle.csv')


arTime = random_dates('2024-04-01', '2024-04-30', 100, 's', seed=None)
df["date_of_sale"]=df.apply(lambda row: arTime[row.name], axis=1)

multiplier = 250
while len(df) < 1000000:
    p=random.randint(2,100)
    toMultiply=df[p-1:p]
    toMultiply = pd.concat([toMultiply] * multiplier, ignore_index = True)
    arTime = random_dates('2024-04-01', '2024-04-30', multiplier, 's', seed=None)
    toMultiply["date_of_sale"]=toMultiply.apply(lambda row: arTime[row.name], axis=1)

    df = pd.concat([df, toMultiply], ignore_index = True)


df = df.sample(frac=1, ignore_index= True)
# df.reset_index(drop=True)

# df.index += 1
df.to_csv('../src/main/resources/gameTitlesOneM.csv',index=False)