In [11]:
import pandas as pd

df = pd.read_csv('../src/main/resources/SampleGameTitle.csv')

# Quick Analysis: the csv consist of 2000 plus unique game title.
print(f"There are {df['game_name'].unique().size} unique game title")

df.info

There are 2133 unique game title

<bound method DataFrame.info of                game_name game_code  type  cost_price   tax  sale_price
0         Counter-Strike        pc     2        9.17  0.09        9.99
1          Day of Defeat        pc     2        4.58  0.09        4.99
2     Deathmatch Classic        pc     2        4.58  0.09        4.99
3               Ricochet        pc     2        4.58  0.09        4.99
4        Team Fortress 2        pc     2        0.00  0.09        0.00
...                  ...       ...   ...         ...   ...         ...
2159           Bamboo EP        pc     2        0.00  0.09        0.00
2160    Shot Shot Tactic        pc     2        3.66  0.09        3.99
2161                 Ra2        pc     2        0.00  0.09        0.00
2162       Paintball 707        pc     2        4.58  0.09        4.99
2163          Technoball        pc     2        0.00  0.09        0.00

[2164 rows x 6 columns]>

Use the code below to randomize the title. Also, it takes the first 100 rows. With that, the game_no (as per requirement 1 to 100) is then assigned.

In [26]:
#  Random the sequence
randomized = df.sample(frac=1, ignore_index= True)
randomized.reset_index(drop=True)
randomized.head(50)

               game_name game_code  type  cost_price   tax  sale_price
0           Kingdom Wars        pc     1        0.00  0.09        0.00
1                 ONRAID        pc     1        9.17  0.09        9.99
2       Mysterious Space        pc     2        9.17  0.09       10.00
3            Gemini Wars        pc     2       13.75  0.09       14.99
4           Actua Golf 3        pc     2        4.58  0.09        4.99
5          Path of Exile        pc     1        0.00  0.09        0.00
6          Insecters War        pc     2        0.00  0.09        0.00
7             Scary Girl        pc     2        6.41  0.09        6.99
8          Rally Copters        pc     2        6.41  0.09        6.99
9               NBA 2K17        pc     2       55.04  0.09       59.99
10                  Crea        pc     2       13.75  0.09       14.99
11            Hauntsters        pc     2        4.58  0.09        4.99
12             Sky Rogue        pc     2        9.17  0.09        9.99
13            MapleStory        pc     1        0.00  0.09        0.00
14           Below Kryll        pc     2        4.58  0.09        4.99
15               Alganon        pc     1        0.00  0.09        0.00
16             Jamestown        pc     2        9.17  0.09        9.99
17              Positron        pc     2        0.00  0.09        0.00
18           ManaCollect        pc     2        2.56  0.09        2.79
19             WolfQuest        pc     2        9.17  0.09        9.99
20      Lost Planet(r) 2        pc     2       18.34  0.09       19.99
21           Bombernauts        pc     2        9.17  0.09        9.99
22    AoF Chess Club 2.0        pc     2        9.17  0.09        9.99
23  Total War: WARHAMMER        pc     2       55.04  0.09       59.99
24           Lost Castle        pc     2        9.17  0.09        9.99
25              Altitude        pc     2        0.00  0.09        0.00
26          Oh No! Bugs!        pc     2        4.58  0.09        4.99
27   Pixel Cup Soccer 17        pc     2        9.17  0.09        9.99
28                Chaser        pc     2        4.58  0.09        4.99
29      Rivals of Aether        pc     2       13.75  0.09       14.99
30    Jet Racing Extreme        pc     2        3.66  0.09        3.99
31                Impire        pc     2       18.34  0.09       19.99
32       Galaxy Admirals        pc     2        1.83  0.09        1.99
33             Dark Eden        pc     1        0.00  0.09        0.00
34         Tricky Towers        pc     2       13.75  0.09       14.99
35                Arma 2        pc     2       11.92  0.09       12.99
36            Blockships        pc     2        6.41  0.09        6.99
37               Butsbal        pc     2        2.74  0.09        2.99
38      Ms. Splosion Man        pc     2        9.17  0.09        9.99
39                 CATS!        pc     2        9.17  0.09        9.99
40  Random Access Murder        pc     2        2.74  0.09        2.99
41            DiRT Rally        pc     2       55.04  0.09       59.99
42               SinaRun        pc     2        2.74  0.09        2.99
43        T-Kara Puzzles        pc     2        2.74  0.09        2.99
44           BattleSpace        pc     1        0.00  0.09        0.00
45    Chicken Invaders 2        pc     2        3.66  0.09        3.99
46        Sphere Complex        pc     2        9.17  0.09        9.99
47              The Isle        pc     2       18.34  0.09       19.99
48          Blind Blades        pc     2        4.58  0.09        4.99
49                 BRINK        pc     2        7.33  0.09        7.99

In [28]:
randomized.index += 1
randomized[:100].to_csv('../src/main/resources/100GameTitle.csv',index_label='game_no')

In [3]:
import numpy as np
def random_dates(start, end, n, freq, seed=None):
    if seed is not None:
        np.random.seed(seed)

    dr = pd.date_range(start, end, freq=freq)
    return pd.to_datetime(np.sort(np.random.choice(dr, n, replace=False)))

random_dates('2024-04-01', '2024-04-30', 91, 's', seed=None)

DatetimeIndex(['2024-04-01 09:33:48', '2024-04-02 07:00:26',
               '2024-04-02 08:08:34', '2024-04-02 14:18:13',
               '2024-04-03 12:56:18', '2024-04-03 14:23:17',
               '2024-04-03 15:33:42', '2024-04-03 22:52:26',
               '2024-04-04 05:53:16', '2024-04-04 09:10:33',
               '2024-04-04 09:23:02', '2024-04-04 15:32:13',
               '2024-04-04 16:09:03', '2024-04-04 16:10:02',
               '2024-04-04 17:13:23', '2024-04-05 14:36:59',
               '2024-04-05 18:07:44', '2024-04-06 09:20:55',
               '2024-04-06 21:17:03', '2024-04-07 02:57:02',
               '2024-04-07 13:00:59', '2024-04-07 16:28:28',
               '2024-04-07 18:42:06', '2024-04-07 19:50:28',
               '2024-04-07 20:01:37', '2024-04-08 06:29:27',
               '2024-04-08 09:37:43', '2024-04-08 12:26:44',
               '2024-04-08 17:05:17', '2024-04-09 03:13:01',
               '2024-04-09 13:31:12', '2024-04-09 22:39:29',
               '2024-04-10 08:22:42', '2024-04-10 14:57:22',
               '2024-04-10 16:28:33', '2024-04-10 20:02:35',
               '2024-04-10 23:09:27', '2024-04-11 01:44:35',
               '2024-04-12 09:18:17', '2024-04-12 19:38:07',
               '2024-04-13 02:42:52', '2024-04-13 04:48:12',
               '2024-04-13 18:16:27', '2024-04-14 01:51:12',
               '2024-04-14 04:23:55', '2024-04-14 07:36:28',
               '2024-04-14 09:11:53', '2024-04-14 11:33:58',
               '2024-04-14 12:16:35', '2024-04-14 20:06:29',
               '2024-04-15 03:29:34', '2024-04-15 04:43:43',
               '2024-04-15 07:51:53', '2024-04-15 22:55:24',
               '2024-04-16 04:27:57', '2024-04-16 12:33:11',
               '2024-04-17 14:48:01', '2024-04-17 19:41:35',
               '2024-04-18 15:28:15', '2024-04-19 20:18:29',
               '2024-04-20 01:07:44', '2024-04-20 01:38:14',
               '2024-04-20 01:57:51', '2024-04-20 09:47:40',
               '2024-04-20 23:11:23', '2024-04-21 07:20:59',
               '2024-04-21 07:48:36', '2024-04-21 11:27:40',
               '2024-04-22 11:58:30', '2024-04-22 18:45:42',
               '2024-04-22 22:42:45', '2024-04-23 06:33:56',
               '2024-04-23 09:26:16', '2024-04-23 10:09:03',
               '2024-04-23 23:47:52', '2024-04-24 09:54:02',
               '2024-04-24 14:19:25', '2024-04-24 15:23:31',
               '2024-04-24 19:33:05', '2024-04-24 23:12:58',
               '2024-04-24 23:42:29', '2024-04-25 04:56:54',
               '2024-04-25 21:34:21', '2024-04-27 08:17:38',
               '2024-04-27 16:26:30', '2024-04-27 17:54:29',
               '2024-04-28 11:24:22', '2024-04-28 23:44:47',
               '2024-04-29 00:14:22', '2024-04-29 01:06:40',
               '2024-04-29 20:13:10'],
              dtype='datetime64[ns]', freq=None)

# Using this to quickly generate 1K game_sales records.

In [146]:
import random
import pandas as pd
df = pd.read_csv('../src/main/resources/100GameTitle.csv')


arTime = random_dates('2024-04-01', '2024-04-30', 100, 's', seed=None)
df["date_of_sale"]=df.apply(lambda row: arTime[row.name], axis=1)

multiplier = 20
while len(df) < 1000:
    p=random.randint(2,100)
    toMultiply=df[p-1:p]
    toMultiply = pd.concat([toMultiply] * multiplier, ignore_index = True)
    arTime = random_dates('2024-04-01', '2024-04-30', multiplier, 's', seed=None)
    toMultiply["date_of_sale"]=toMultiply.apply(lambda row: arTime[row.name], axis=1)

    df = pd.concat([df, toMultiply], ignore_index = True)


df = df.sample(frac=1, ignore_index= True)
# df.reset_index(drop=True)

# df.index += 1
df[:1000].to_csv('../src/main/resources/gameTitlesOneK.csv',index=False)

# Using this to quickly generate 1M game_sales records.

In [4]:
import random
import pandas as pd
df = pd.read_csv('../src/main/resources/100GameTitle.csv')


arTime = random_dates('2024-04-01', '2024-04-30', 100, 's', seed=None)
df["date_of_sale"]=df.apply(lambda row: arTime[row.name], axis=1)

multiplier = 250
while len(df) < 1000000:
    p=random.randint(2,100)
    toMultiply=df[p-1:p]
    toMultiply = pd.concat([toMultiply] * multiplier, ignore_index = True)
    arTime = random_dates('2024-04-01', '2024-04-30', multiplier, 's', seed=None)
    toMultiply["date_of_sale"]=toMultiply.apply(lambda row: arTime[row.name], axis=1)

    df = pd.concat([df, toMultiply], ignore_index = True)


df = df.sample(frac=1, ignore_index= True)
# df.reset_index(drop=True)

# df.index += 1
df[:1000000].to_csv('../src/main/resources/gameTitlesOneM.csv',index=False)